def time_to_human(time: float|int) -> str: ...

def calc_time(function) -> None: ...


class ActivationFunction:
	@staticmethod
	def sigmoid(x: float) -> float: ...

	@staticmethod
	def tanh(x: float) -> float: ...

	@staticmethod
	def relu(x: float) -> float: ...
