

def calc_time(function) -> None: ...

def time_to_human(time: float|int) -> str: ...

# def show_progress(now: int, total: int, time_manager: TimeManager=None, length: int=30, icons: str='█ ') -> None: ...

def cprint(text, color: str='red', sep: str='\n', ret: bool=False) -> None|str: ...


class ActivationFunction:
	@staticmethod
	def sigmoid(x: float) -> float: ...

	@staticmethod
	def tanh(x: float) -> float: ...

	@staticmethod
	def relu(x: float) -> float: ...
